### ISSUE TITLE
Process very slow to quit (360 seconds) when scrypt is missing

### ISSUE THREAD

**Issue by nirgal** [pooler/electrum-ltc#131]
Hi

Here's a minor issue:

I'm using Debian. When I run Electrum-LTC-3.0.5.1/electrum-ltc I get this message:
    Warning: package scrypt not available, using fallback
then everything works ok... until I want to quit. When I try to, the windows disappear but the python process continues running indefinitely.

The problem was fixed by installing the package python3-scrypt.

**Comment by pooler** [comment]
This is expected behavior. Without the `scrypt` package, which provides compiled code for the hashing algorithm, synchronization is very CPU intensive and over 100 times slower.

Note that the `scrypt` package is automatically installed if you install Electrum-LTC via pip, so the issue can only arise if one runs the program without installing it.

I made a commit yesterday which adds "synchronization could be very slow" to the warning message. This should help users understand what's going on.

**Comment by nirgal** [comment]
I uninstalled python3-scrypt to make more test, because I don't think we understand each other.
I do understand this is an unusual setup.

Synchronisation takes a few seconds, I have no trouble there. I don't have a problem with the warning message either.

My problem: When in the menu, I select File/Quit, the windows disappear, like if the program was terminated. But `ps` shows that the process is still running. I started the program from a terminal and Control+C doesn't work either: It only displays "^C" but does not quit. The only way to stop the python3 process is to kill it from another terminal. I waited over 5 full minutes. (I will update this post on https://github.com/pooler/electrum-ltc/issues/131 in a while).

That bug does not occur when scrypt is installed.

**Comment by nirgal** [comment]
I cannot reproduce the problem any more (scrypt still uninstalled).
Now it takes a second for the process to quit.
Fell free to close the issue.

**Comment by pooler** [comment]
I just tried reproducing this. I uninstalled the `scrypt` package and ran 3.0.5.1 from the official tarball. Initial headers download went fine (because no verification is performed), and I could exit just fine.
If, however, the blockchain is not completely synced and I try to exit while the program is verifying a chunk of headers, the process takes a long time to finish, exactly as you described. But this is exactly the behavior I expected.

Are you sure that when you exited your blockchain was fully synchronized? If so, please try again. What does the network dialog say? What output do you get in the terminal after you click on Quit?
