### ISSUE TITLE
Multisig different address format

### ISSUE THREAD

**Issue by joancomarti** [pooler/electrum-ltc#140]
I have a 2-5 multisig account with the following address: M9wBHGJQTrxrp7GLJ23A5qv9XfAmuxQrPt
When I order to my exchange a payment to that address, it appeared in the transaction:
https://api.blockcypher.com/v1/ltc/main/txs/6355300e5e96b261553ae8ec04663104b0378004ed4c032c817bab5704437c1a
BUT the import (0.37) corresponds to the address:
33j2yNtSWk7S1bzSC93pGCfkCxaKyxuZB9
I though that it was a mistake of the exchange but the Electrum mutisig wallet shows correctly the transaction with the address: M9wBHGJQTrxrp7GLJ23A5qv9XfAmuxQrPt
Is there any place where I can read how this addresses are generated and why there is this double coding in Electrum?
Thanks!

**Comment by pooler** [comment]
`33j2yNtSWk7S1bzSC93pGCfkCxaKyxuZB9` and `M9wBHGJQTrxrp7GLJ23A5qv9XfAmuxQrPt` are effectively the same address, just represented differently.

This is not specific to Electrum. A few months ago Litecoin changed the official format of its P2SH addresses so that they start with `M` instead of `3`. See the blog post [here](https://blog.litecoin.org/litecoin-core-v0-14-2-release-ab6d2217405f). You can convert between old and new format [here](https://litecoin-project.github.io/p2sh-convert/).
