### ISSUE TITLE
Electrum Wallet Says Disconnected

### ISSUE THREAD

**Issue by DeonMadanjith** [pooler/electrum-ltc#156]
Hi all,

I installed version 3.0.6.2, transferred a few LTC as a test from my Nano to the wallet.  However, the electrum wallet only says disconnected.  Red Buttom bottom right. Hence i cannot see the coins.  I checked on the blockchain, the transactions are confirmed.  Please help.  I am using Windows.  Its been a week now.  I tried everything, no success.

**Comment by raymondcarl** [comment]
@DeonMadanjith 

My first step would be to make sure there is nothing blocking the firewall.  The second step would be to try and manually add nodes, but I have never had that problem with Electrum.  Have you tried those steps?

**Comment by DeonMadanjith** [comment]
@raymondcarl 

Should i disable the firewall?  How do manually add nodes?   I tried everything including manually  selecting servers...etc.  Nothing works.  I even re-downloaded the wallet, plugged in my seed.  I tried un-ticking the SSL certs and only using proxy.

**Comment by raymondcarl** [comment]
@DeonMadanjith 

No, you shouldn't have to disable to firewall and it isn't a good idea.  However, 1 quick way to troubleshoot is to disable the firewall and see if you are able to connect.  If so, you know you have a firewall problem.  Then, you turn the firewall back on immediately and try to figure out which port is being blocked.  If it still doesn't work, then you know it's not a firewall problem.  Are you on a personal network, etc.?  If you are running sensitive applications etc, then it may not be a good idea to disable the firewall even if only for a few minutes.  Is there anything else on your network blocking / filtering traffic?

Note:  this is an old thread and refers to Ubuntu, but a guy had a similar issue and it was because the firewall was blocking port 50001.  I suspect he added the rule previously, but just needed to restart the firewall program for Ubuntu (UFW).

https://ubuntuforums.org/showthread.php?t=2187069

**Comment by pooler** [comment]
One other thing I would try is clearing your data directory (make a backup first).

**Comment by DeonMadanjith** [comment]
Hi Guys,  Just an update.  Unfortunately I am at the mercy of my Employers Firewall &Security Policy, hence I cannot turn off.  I will download the Electrum LTC on a different Computer, then plug in my seed and see if i can recover the coins.  I will keep you guys updated.

**Comment by raymondcarl** [comment]
@pooler I think this issue should be closed.  This is a firewall problem.
