### ISSUE TITLE
Ledger 1.4.1 firmware / Litecoin app no longer working with segwit wallet

### ISSUE THREAD

**Issue by BrotherBuford** [pooler/electrum-ltc#163]
Ledger devices upgraded to the just released 1.4.1 firmware now cause a "Firmware version (or Litecoin app) too old for segwit support.  Please update at https://www.ledgerwallet.com" error when attempting to use with a segwit wallet file. The Bitcoin app is now being used as a shared library on Ledgers for all Bitcoin-based coins and needs to be installed even if Bitcoin is not used, so the version number being reported may be from that app instead of the Litecoin one.

**Comment by pooler** [comment]
Electrum requires at least version 1.1.10, while Electrum-LTC requires at least version 1.1.9, so the version itself may not be the actual problem. I suspect the issue is caused by improper version checking, which has been fixed in Electrum 3.1.

Unfortunately I do not have a Ledger at hand, so I am unable to verify. Could somebody please test the current git master?

**Comment by BrotherBuford** [comment]
The newest release version of Electrum-LTC (3.1.2.1) corrects this issue.  I just tested it with a Ledger and it works as expected with a segwit wallet.
