### ISSUE TITLE
ELECTRUM 3.1.3.1 WALLET DOES NOT SHOW TRANSACTIONS ANYMORE

### ISSUE THREAD

**Issue by OGHIS** [pooler/electrum-ltc#192]
Hello guys, 

>> I got my first LTC earnings on ELECTRUM WALLET (previous version) on : 13 december 2017

>> I INSTALLED this summer : ELECTRUM 3.1.3.1 version

>>  AND I do not see any earnings ANYMORE since 14 august 2018

CAN SOMEONE EXPLAIN ME WHY ?

Is there any possibility that mining operations stopped after 8 months ?

Or did I make a mistake with my wallet configuration ? (But I let the INSTALL process run automatically, so...)

THANKS A LOT.

Olivier

**Comment by OGHIS** [comment]
IF IT CAN HALP anybody to understand, here's how it looks.

![capture wallet](https://user-images.githubusercontent.com/44125123/46910325-034df800-cf43-11e8-9fb5-501631e175dd.PNG)

**Comment by pooler** [comment]
Sorry but I do not understand what your problem is. I do not see anything obviously wrong with the screenshot that you posted. All I can tell is that you've been receiving small transactions to this wallet, and then yesterday you sent out your balance, as you had apparently already done before. Are transactions missing perhaps? If so, could you post the transaction IDs?

**Comment by G4RM8n** [comment]
tengo un problema con la wallet, no aparecen los enviados de litoshi a la cuenta, que puedo haber pasado y ya fueron enviados y no aparecen..      Gracias por su atención .    ATT:  Germán.

**Comment by pooler** [comment]
No response from OP, closing.

If still using 3.1.3.1, you must update to the latest version (currently 3.3.6.1,see https://electrum-ltc.org).
