### ISSUE TITLE
PLEASE HELP! how I can donate?

### ISSUE THREAD

**Issue by rcuskov** [pooler/electrum-ltc#204]
I have searches key to shoot my trouble here in issues. And I want to send a little litecoin to Pooler!

**Comment by rcuskov** [comment]
*searched

**Comment by rcuskov** [comment]
and found

**Comment by pooler** [comment]
As I've stated since the beginning, I'm not accepting personal donations for Electrum-LTC.

There is a donation fund (LectrumELqJWMECz7W2iarBpT4VvAPqwAv), which has been used to support project expenses and to thank major contributors other than myself. _However_, if you want to donate, right now I would suggest donating directly to servers instead, by using the builtin client functionality (`Help` > `Donate to server`). Running a public Electrum server is a valuable service to the community, but there are costs, both in terms of time and money, so donations to server operators contribute to the global health of the ecosystem.
