### ISSUE TITLE
Error during signing transaction with Trezor 

### ISSUE THREAD

**Issue by sorooris** [pooler/electrum-ltc#247]
OS: Win10
App: Electrum-LTC 3.3.8.1 (latest)
Device: Trezor model T 2.3.3 (latest)

**Steps to reproduce:**
1. Recover a standard wallet with a Trezor device (any model) with an available balance
2. Prepare a transaction
3. Sign the transaction

**Expected result:**
Transaction is signed successfully.

**Actual result:**
Transaction results in an error and a modal with a "b'\xd1\x1d\x9c\xbdH\xbe\xdf|r0\x08\x04\xb5\xed\xf8\xd5\x1a0\xa7N}\xeck\xef\x85\x9c7!\xcfn\xc0\xe9'" message is displayed instead.

**Note:**
Signing works with the Electrum BTC, would be nice if you could release new builds.

**Screenshot:**
![image](https://user-images.githubusercontent.com/10185314/95084788-a8f56580-071e-11eb-8403-73f64dda07e6.png)

**Comment by goodc0re** [comment]
Having the same problem. Funds on bech32 Litecoin addresses derived from a Trezor are therefore unspendable.

**Comment by Emily844** [comment]
Having the same issue with Electrum LTC. Cannot send LTC to my Trezor Wallet One.

**Comment by 3rdIteration** [comment]
I just had a look and can reproduce the issue.

The good news is that it has also been fixed in the repository, just not included in a published release yet. It also works fine if you download the Github repository and run it from there.

0.     Install python 3. (I tested this with Python 3.8.6 64bit today and it works fine on Windows)
1.	Download the source code and unzip. (Or clone with Github as I did)
2.	Install dependencies
a.	pip install -r ./contrib/requirements/requirements.txt
b.	pip install -r ./contrib/requirements/requirements-hw.txt
c.	pip install pyqt5
3.	download and install a libsecp256k1 dll
a.	You can download a pre-build dll here: https://www.nuget.org/packages/Secp256k1.Net
b.	Extract the secp256k1.dll for your environment and rename to libsecp256k1-0.dll and place it in the electrum_ltc folder in the electrum github repo. (Eg: my environment is windows, 64bit, so the file I want is in secp256k1.net.0.1.55\content\native\win-x64, and I placed it in the folder GitHub\electrum-ltc\electrum_ltc)
4.	Run python via “Python run electrum"

**Comment by gurpalw** [comment]
@3rdIteration Can confirm that your solution works... @Emily844 @goodc0re you need to build electrum-ltc from source

**Comment by Emily844** [comment]
@gurpalw Thank you for the confirmation. I got stuck with libsecp256k1, I read another threads, but I was not able to solve this issue. Seems like I just wait for the 4.X release.
E | ecc_fast | libsecp256k1 library failed to load. exceptions: [FileNotFoundError("Could not find module 'C:\\Users\\Lucie\\Downloads\\electrum-ltc-master\\electrum_ltc\\libsecp256k1-0.dll' (or one of its dependencies). Try using the full path with constructor syntax."), FileNotFoundError("Could not find module 'libsecp256k1-0.dll' (or one of its dependencies). Try using the full path with constructor syntax.")]
Error: Failed to load libsecp256k1.

**Comment by Emily844** [comment]
@gurpalw  Thank you for the confirmation. I got stuck with libsecp256k1, I read another threads, but I was not able to solve this issue. Seems like I just wait for the 4.X release.
E | ecc_fast | libsecp256k1 library failed to load. exceptions: [FileNotFoundError("Could not find module 'C:\Users\Name\Downloads\electrum-ltc-master\electrum_ltc\libsecp256k1-0.dll' (or one of its dependencies). Try using the full path with constructor syntax."), FileNotFoundError("Could not find module 'libsecp256k1-0.dll' (or one of its dependencies). Try using the full path with constructor syntax.")]
Error: Failed to load libsecp256k1.

**Comment by 3rdIteration** [comment]
> @gurpalw Thank you for the confirmation. I got stuck with libsecp256k1, I read another threads, but I was not able to solve this issue. Seems like I just wait for the 4.X release.
> E | ecc_fast | libsecp256k1 library failed to load. exceptions: [FileNotFoundError("Could not find module 'C:\Users\Name\Downloads\electrum-ltc-master\electrum_ltc\libsecp256k1-0.dll' (or one of its dependencies). Try using the full path with constructor syntax."), FileNotFoundError("Could not find module 'libsecp256k1-0.dll' (or one of its dependencies). Try using the full path with constructor syntax.")]
> Error: Failed to load libsecp256k1.

Just download the libsecp256k1 from my lazybuilds repo and it will work. (Full walkthrough here: https://youtu.be/3rHLGPkgYGM)

**Comment by pooler** [comment]
Binaries are now available for version 4.0.9.1, which fixes this.

**Comment by bosomt** [comment]
I was able to send tx https://ltc1.trezor.io/tx/130e1ada9c200916813dfdab9e045769220be462a94df4213a589f88b0292014 

version 4.0.9.1
FW 2.3.5
Nixos
