### ISSUE TITLE
Can't send LTC

### ISSUE THREAD

**Issue by yleyvag** [pooler/electrum-ltc#265]
I'm trying to send LTC to another Electrum wallet but I can't, everytime I click the send button I'm seeing this message. The address I'm sending was generated by Electrum wallet, I don't know what can be wrong since it was working some days ago. Also, "max" button isn't working neither, I click it and nothing happens. It seems the generated address from Electrum Wallet is wrong because I'm not seeing this problems with addresses generated by other wallets.

![image](https://user-images.githubusercontent.com/17904060/111811709-b73ed480-88ad-11eb-9b2c-848534d2c8da.png)

**Comment by pooler** [comment]
Please provide the exact version of Electrum-LTC you are using, and the full address you are trying to send to.
Also, did you enable Lightning by any chance? Please provide detailed information about the type of wallet you are using (you can see this under `Wallet` > `Information`).

**Comment by yleyvag** [comment]
Electrum LTC version: 4.0.9.2
Type of wallet: standard
I'm trying to send to LNJJfGxqhZ6yLh9HB9WKH7a2qFpeDzQXEk and LNSGMEn9KXX7t5y5GSVRjnsJBatrtismcA
I haven't enable Lightning, I never have used that.

**Comment by pooler** [comment]
Thank you. I just pushed a commit that should prevent Electrum-LTC from mistaking legacy addresses starting with `LN` for BOLT-11 invoices. This fix will be included in the upcoming 4.0.9.3 release.

**Comment by yleyvag** [comment]
thank you for your fast help and support, can you tell me when this update will be released?

**Comment by pooler** [comment]
> can you tell me when this update will be released?

As soon as Adrian finds some time to build the new binaries. Probably a few days.

**Comment by kazzkiq** [comment]
Hello, just pinging this thread as it's been a week already and I can't move my LTC in the meantime.

Any idea of when the new binaries will be available?

**Comment by yleyvag** [comment]
my solution was to generate a new LTC address in the meantime, another that doesn't starts with LN, those that starts with LN stills there unused.

**Comment by kazzkiq** [comment]
I don't have control over it since it's an exchange address.

The possible solution would be to import my priv. key to another trustable LTC client and try the transaction from there, but there are not many trustable LTC wallets out there as you can imagine, and putting my private keys into other clients I don't know/trust is not exactly something I feel wise to do at the moment.

**Comment by pooler** [comment]
Unfortunately I cannot say when the new binaries will be ready -- it is outside of my control.

If you cannot run the new version from source (4.0.9.3 has already been tagged in the repo), one possible workaround for now is to make a transaction with multiple outputs, since such a transaction should not trigger the issue. If you only need to send to one address, you could split the amount in half. For instance, to send 0.01 LTC, you could do:
```
LNJJfGxqhZ6yLh9HB9WKH7a2qFpeDzQXEk,0.005
LNJJfGxqhZ6yLh9HB9WKH7a2qFpeDzQXEk,0.005
```
This is a hack, of course, but it should do the trick.

**Comment by pooler** [comment]
Binaries for 4.0.9.3 are now available on the official website.

**Comment by Hub-O-Gits** [comment]
What about the Max button not working? I have that problem as well.
