### ISSUE TITLE
Transaction still pending with 0 confirmations after 3 days

### ISSUE THREAD

**Issue by trolleypoleking** [pooler/electrum-ltc#27]
I've been able to send a small transaction without an issue since this one stalled. The pending transaction periodically disappears from my wallet then comes back. Not too sure what's going on here. I've tried to re-broadcast the transaction from the commandline but i'm an inexperienced user and am not entirelly sure what I am doing. Any help would be greatly appreciated. 

Here's the transaction on the block explorer:

https://block-explorer.com/tx/8bc06a3b1109bd27a52676221b77f24c6f164a8fe1701e4cbfdb8884d18ac719

**Comment by pooler** [comment]
It looks like this transaction has a high-S signature, which explains why miners are rejecting it. Which version of Electrum-LTC did you use to create it?

**Comment by trolleypoleking** [comment]
I downloaded electrum-ltc from the official site about a month ago, i'd say. Not sure what version it was then. I upgraded to the current version after the transaction stalled. Anyway it seems to have gone through now. Showing 56 confirmations on electrum. I don't know what a High-S signature is or how i managed to use one in the transaction but it all seems to have worked itself out.

**Comment by trolleypoleking** [comment]
Although the transaction is not showing up as confirmed on either blockchain explorer and the balance in electrum-ltc still shows the outgoing as 'unconfirmed'.

**Comment by pooler** [comment]
After the recent soft fork, the Litecoin network only accepts transactions with low-S signatures (more info [here](https://www.reddit.com/r/litecoin/comments/3z7551/update_litecoin_0104_released_update_immediately/)). Before version 2.5, Electrum produced high-S signatures, and that's why the network is rejecting your transaction.

Could you please try to recreate your wallet from your seed, and see if the transaction shows up? (File > Create/Restore > Restore)

**Comment by trolleypoleking** [comment]
Just recreated from seed and now the transaction is showing up as pending again with zero confirmations. Weird.

**Comment by pooler** [comment]
OK, now please try this: go to Tools > Network, disable automatic server selection and connect to electrum-ltc.bysh.me, port 50002 instead. Then restart Electrum-LTC and try again recreating your wallet from its seed.

**Comment by trolleypoleking** [comment]
Okay, done. The transaction is no longer showing up.

**Comment by pooler** [comment]
At this point, if you want to stay on the safe side, I would suggest that you create a brand new wallet and send all your funds to it using the wallet you just recreated. Then you can make a new transaction to replace the invalid one.

**Comment by trolleypoleking** [comment]
I think that's the best course of action. Thanks for the help.

**Comment by TheMaverickProgrammer** [comment]
Reopening this because this is the same problem I have except it shows up on the chain explorer. I cannot transfer funds from old wallet to the new one to send out to my trading account.

https://blockchain.info/tx/5982f0f0deef4c6a39319c419dbd3cd27b0585c3c70f5810d39c8a7c651848f6

What can I do to get my money approved or have I lost it all??

**Comment by pooler** [comment]
@TheMaverickProgrammer Are you sure you're at the right place? This is Electrum for Litecoin, and yours is a Bitcoin transaction.
