### ISSUE TITLE
Waiting for fee estimates...

### ISSUE THREAD

**Issue by mhulscher** [pooler/electrum-ltc#65]
On 2.9.3.1

Looking at the main window, the status bar at the bottom will often for very long times show 'Waiting for fee estimates...' This can be annoying when trying to read the balance in the status bar.

**Comment by pooler** [comment]
This happens because, on the server, Litecoin Core fails to provide a fee estimate for a target of 2 blocks (i.e. `estimatefee 2` returns -1).

You must have enabled dynamic fees in the preferences to get this issue. I suggest turning them off. By default dynamic fees are disabled in Electrum-LTC, for two reasons: they are not very useful at the moment (there's much, much fewer transactions being sent compared to Bitcoin, and blocks are still practically empty), and sometimes Litecoin Core has issues providing fee estimates (probably for the same reason).

**Comment by mhulscher** [comment]
Thank you. Disabling dynamic fees is an acceptable workaround. If you don't consider this a bug then please close the issue.
